### ISSUE TITLE
Problem running images using the 'net/http' library

### ISSUE THREAD

**Issue by ap0** [zulily/boilerplate#4]
Trying to dockerize a program that uses the "net/http" library, I encountered an issue when running it:

```
➜  splitlab-api git:(master) ✗ make dockerize && docker run zulily/splitlab-api:ad7944f
building splitlab-api binary for inclusion in Docker image...
 building Docker image 'zulily/splitlab-api'...
Sending build context to Docker daemon 8.663 MB
Sending build context to Docker daemon
Step 0 : FROM scratch
 --->
Step 1 : ADD ./splitlab-api /splitlab-api
 ---> 29d9d2579619
Removing intermediate container 88a5b8caf3c8
Step 2 : ENTRYPOINT /splitlab-api
 ---> Running in 8f023100c541
 ---> ed8672c0602b
Removing intermediate container 8f023100c541
Successfully built ed8672c0602b
no such file or directoryFATA[0000] Error response from daemon: Cannot start container e202a47ede3f2d284c5679f2a790e1c5dc69beb65425b9c321db7d7578e806e9: no such file or directory
```

After some Googling, I found this: http://blog.xebia.com/2014/07/04/create-the-smallest-possible-docker-container/ and found that it was because Go is not actually statically linking all libraries.

The workaround I found was here: https://github.com/golang/go/issues/9344, which was to add `-installsuffix cgo` to the `godep go build` command in build/Dockerfile.  Doing this allowed the image to run in a `scratch` container.  The Dockerfile command now looks like this: `CMD ["sh", "-c", "godep go build -o ${BINARY} -a -installsuffix cgo -tags netgo -ldflags -s -ldflags \"-X main.BuildSHA ${GIT_SHA}\" "]`

I'm not sure if this is a great practice, as it seems to be a workaround rather than a stable solution, but it would be worth investigating how to get around this.

**Comment by dcarney** [comment]
Good catch.  Looks like the static linking behavior changed in go 1.4:  

https://groups.google.com/forum/#!topic/golang-dev/ajODMUyOhPI

> This meant that the previously common 
> idiom "go build -a -tags netgo" no longer rebuilt the standard library 
> with the netgo tag. 
> 
> I believe the correct response to is to use `go build -a -tags netgo -installsuffix netgo my/binary`

After reading up on this, it seems like `installsuffix` isn't just a temporary workaround,  and that other projects are using it as a legit fix for this issue: 

https://github.com/deis/deis/pull/3133/files

https://github.com/docker/docker/pull/10087/files
